const fs = require('fs');

const chunk = `
<section class="ssec bwhite" id="itinerario"><div class="sin">
<div class="strow"><div class="sgl"></div><h2 class="stitle bc">Itinerario dia a dia</h2><div class="stnum">8</div></div>
<div style="border-bottom:1px solid var(--border);display:flex;overflow-x:auto;margin-bottom:16px">
<div class="itab on" onclick="switchItin(this,'itin-d0')" style="padding:8px 16px;font-family:'Barlow Condensed',sans-serif;font-size:13px;font-weight:700;letter-spacing:1px;cursor:pointer;border:none;background:none;color:var(--gold);border-bottom:3px solid var(--gold);margin-bottom:-1px">Día 1</div>
</div>
<div class="itin-panel on" id="itin-d0">
<div>
<div class="itin-step" style="display:flex;gap:14px;padding-bottom:20px"><div class="itin-dot on" style="width:32px;height:32px;border-radius:50%;background:var(--gold-light);border:2px solid var(--gold);display:flex;align-items:center;justify-content:center;font-size:13px;flex-shrink:0;z-index:1">🏛️</div><div style="flex:1;padding-top:4px"><div style="font-size:10px;font-weight:700;color:var(--gold-dark);text-transform:uppercase;letter-spacing:1px;margin-bottom:3px">9:00 am</div><div style="font-family:'Barlow Condensed',sans-serif;font-size:16px;font-weight:800;color:var(--text);margin-bottom:5px">Partida en el centro</div><div style="font-size:12px;color:#555;line-height:1.65;margin-bottom:8px">Encuentro en la Plaza de Bolívar con guía.</div><div style="display:flex;flex-wrap:wrap;gap:5px"><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Centro histórico</span><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Plaza</span></div></div></div>
<div class="itin-step" style="display:flex;gap:14px;padding-bottom:20px"><div class="itin-dot on" style="width:32px;height:32px;border-radius:50%;background:var(--gold-light);border:2px solid var(--gold);display:flex;align-items:center;justify-content:center;font-size:13px;flex-shrink:0;z-index:1">🏛️</div><div style="flex:1;padding-top:4px"><div style="font-size:10px;font-weight:700;color:var(--gold-dark);text-transform:uppercase;letter-spacing:1px;margin-bottom:3px">9:30 am</div><div style="font-family:'Barlow Condensed',sans-serif;font-size:16px;font-weight:800;color:var(--text);margin-bottom:5px">Plaza de Bolívar y Catedral</div><div style="font-size:12px;color:#555;line-height:1.65;margin-bottom:8px">Visita a la plaza principal y la Catedral Primada.</div><div style="display:flex;flex-wrap:wrap;gap:5px"><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Catedral</span><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Patrimonio</span></div></div></div>
<div class="itin-step" style="display:flex;gap:14px;padding-bottom:20px"><div class="itin-dot on" style="width:32px;height:32px;border-radius:50%;background:var(--gold-light);border:2px solid var(--gold);display:flex;align-items:center;justify-content:center;font-size:13px;flex-shrink:0;z-index:1">🏦</div><div style="flex:1;padding-top:4px"><div style="font-size:10px;font-weight:700;color:var(--gold-dark);text-transform:uppercase;letter-spacing:1px;margin-bottom:3px">10:30 am</div><div style="font-family:'Barlow Condensed',sans-serif;font-size:16px;font-weight:800;color:var(--text);margin-bottom:5px">Museo del Oro</div><div style="font-size:12px;color:#555;line-height:1.65;margin-bottom:8px">Recorrido por oro precolombino.</div><div style="display:flex;flex-wrap:wrap;gap:5px"><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Museo</span><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Precolombino</span></div></div></div>
<div class="itin-step" style="display:flex;gap:14px;padding-bottom:20px"><div class="itin-dot on" style="width:32px;height:32px;border-radius:50%;background:var(--gold-light);border:2px solid var(--gold);display:flex;align-items:center;justify-content:center;font-size:13px;flex-shrink:0;z-index:1">🍽️</div><div style="flex:1;padding-top:4px"><div style="font-size:10px;font-weight:700;color:var(--gold-dark);text-transform:uppercase;letter-spacing:1px;margin-bottom:3px">12:00 pm</div><div style="font-family:'Barlow Condensed',sans-serif;font-size:16px;font-weight:800;color:var(--text);margin-bottom:5px">Almuerzo de ajiaco</div><div style="font-size:12px;color:#555;line-height:1.65;margin-bottom:8px">Restaurante típico zona universitaria.</div><div style="display:flex;flex-wrap:wrap;gap:5px"><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Ajiaco</span><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Universidad</span></div></div></div>
<div class="itin-step" style="display:flex;gap:14px;padding-bottom:20px"><div class="itin-dot on" style="width:32px;height:32px;border-radius:50%;background:var(--gold-light);border:2px solid var(--gold);display:flex;align-items:center;justify-content:center;font-size:13px;flex-shrink:0;z-index:1">🎨</div><div style="flex:1;padding-top:4px"><div style="font-size:10px;font-weight:700;color:var(--gold-dark);text-transform:uppercase;letter-spacing:1px;margin-bottom:3px">1:30 pm</div><div style="font-family:'Barlow Condensed',sans-serif;font-size:16px;font-weight:800;color:var(--text);margin-bottom:5px">Museo Botero</div><div style="font-size:12px;color:#555;line-height:1.65;margin-bottom:8px">Colección de arte Botero.</div><div style="display:flex;flex-wrap:wrap;gap:5px"><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Museo</span></div></div></div>
<div class="itin-step" style="display:flex;gap:14px;padding-bottom:20px"><div class="itin-dot on" style="width:32px;height:32px;border-radius:50%;background:var(--gold-light);border:2px solid var(--gold);display:flex;align-items:center;justify-content:center;font-size:13px;flex-shrink:0;z-index:1">🕯️</div><div style="flex:1;padding-top:4px"><div style="font-size:10px;font-weight:700;color:var(--gold-dark);text-transform:uppercase;letter-spacing:1px;margin-bottom:3px">3:00 pm</div><div style="font-family:'Barlow Condensed',sans-serif;font-size:16px;font-weight:800;color:var(--text);margin-bottom:5px">Pasaje Rivas y Pasaje Hernández</div><div style="font-size:12px;color:#555;line-height:1.65;margin-bottom:8px">Artesanías y galerías ocultas.</div><div style="display:flex;flex-wrap:wrap;gap:5px"><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Pasajes</span><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Arte</span></div></div></div>
<div class="itin-step" style="display:flex;gap:14px;padding-bottom:20px"><div class="itin-dot on" style="width:32px;height:32px;border-radius:50%;background:var(--gold-light);border:2px solid var(--gold);display:flex;align-items:center;justify-content:center;font-size:13px;flex-shrink:0;z-index:1">🌅</div><div style="flex:1;padding-top:4px"><div style="font-size:10px;font-weight:700;color:var(--gold-dark);text-transform:uppercase;letter-spacing:1px;margin-bottom:3px">4:30 pm</div><div style="font-family:'Barlow Condensed',sans-serif;font-size:16px;font-weight:800;color:var(--text);margin-bottom:5px">Chorro de Quevedo</div><div style="font-size:12px;color:#555;line-height:1.65;margin-bottom:8px">Punto de fundación de Bogotá en 1538.</div><div style="display:flex;flex-wrap:wrap;gap:5px"><span style="background:var(--warm);border:1px solid var(--border);border-radius:4px;padding:2px 8px;font-size:10px;font-weight:700;color:var(--text)">Historia</span></div></div></div>
<div class="itin-step" style="display:flex;gap:14px;padding-bottom:20px"><div class="itin-dot on" style="width:32px;height:32px;border-radius:50%;background:var(--gold-light);border:2px solid var(--gold);display:flex;align-items:center;justify-content:center;font-size:13px;flex-shrink:0;z-index:1">👋</div><div style="flex:1;padding-top:4px"><div style="font-size:10px;font-weight:700;color:var(--gold-dark);text-transform:uppercase;letter-spacing:1px;margin-bottom:3px">6:00 pm</div><div style="font-family:'Barlow Condensed',sans-serif;font-size:16px;font-weight:800;color:var(--text);margin-bottom:5px">Fin del recorrido</div><div style="font-size:12px;color:#555;line-height:1.65;margin-bottom:8px">Despedida en zona céntrica.</div></div></div>
</div></div>
</div></section>
`;

fs.appendFileSync('_lacandelaria2_body.html', chunk, 'utf8');
console.log('Appended itinerario, total:', fs.statSync('_lacandelaria2_body.html').size, 'bytes');
