const seed = require('./seed-rock-al-parque.js');
global.require_orig = require;
const Module = require('module');
const path = require('path');
const origResolve = Module._resolveFilename;
Module._resolveFilename = function(request, ...args) {
  if (request === '@neondatabase/serverless') return path.join(__dirname, 'fake_neon.js');
  return origResolve.call(this, request, ...args);
};
require('fs').writeFileSync(path.join(__dirname, 'fake_neon.js'), 'module.exports = { neon: function(){ return function(){ return []; }; } };');
const fs = require('fs');
const vm = require('vm');
const src = fs.readFileSync(path.join(__dirname, '..', 'api', 'pagina-destino.js'), 'utf8');
const sandbox = { module: { exports: {} }, require, console, process };
sandbox.exports = sandbox.module.exports;
vm.createContext(sandbox);
const wrapped = src + '\nmodule.exports.buildHTML = buildHTML;';
vm.runInContext(wrapped, sandbox, { filename: 'api/pagina-destino.js' });
const d = Object.assign({}, seed.BASE, { fotos: [{ url: seed.HERO }], tags: seed.TAGS, rating: 4.8, total_resenas: 3, creado_en: new Date(), actualizado_en: new Date() });
const html = sandbox.module.exports.buildHTML(d, {}, [], []);
function check(label, cond) { console.log((cond ? 'PASS' : 'FAIL') + ' - ' + label); if (!cond) process.exitCode = 1; }
check('renderiza sin error (len>5000)', typeof html === 'string' && html.length > 5000);
check('Fecha y sede con fecha formateada', html.includes('id="evento-fechas"') && html.includes('10 de Octubre de 2026'));
check('Lineup con 26 artistas', (html.match(/class="ilbl">/g) || []).length >= 26 && html.includes('Valore') && html.includes('Skampida'));
check('Agenda del evento', html.includes('id="agenda"') && html.includes('S&#225;bado 10 de octubre') && html.includes('Apertura de puertas'));
check('Tipos de entrada gratis', html.includes('id="tipos-entrada"') && html.includes('Entrada general') && html.includes('Gratis'));
check('Que llevar / prohibido', html.includes('id="que-llevar"') && html.includes('Protector solar') && html.includes('Ingreso de bebidas alcoh'));
check('Mapa con coordenadas', html.includes('4.658056') || html.includes('4.658056,-74.093889'));
const opens = (html.match(/<div/g) || []).length;
const closes = (html.match(/<\/div>/g) || []).length;
console.log('divs open=' + opens + ' close=' + closes + ' diff=' + (opens - closes));
check('balance de divs', opens === closes);
