const seed = require('./seed-barichara.js');
global.require_orig = require;
const Module = require('module');
const path = require('path');
const origResolve = Module._resolveFilename;
Module._resolveFilename = function(request, ...args) {
  if (request === '@neondatabase/serverless') return path.join(__dirname, 'fake_neon.js');
  return origResolve.call(this, request, ...args);
};
require('fs').writeFileSync(path.join(__dirname, 'fake_neon.js'), 'module.exports = { neon: function(){ return function(){ return []; }; } };');
const fs = require('fs');
const vm = require('vm');
const src = fs.readFileSync(path.join(__dirname, '..', 'api', 'pagina-destino.js'), 'utf8');
const sandbox = { module: { exports: {} }, require, console, process };
sandbox.exports = sandbox.module.exports;
vm.createContext(sandbox);
const wrapped = src + '\nmodule.exports.buildHTML = buildHTML;';
vm.runInContext(wrapped, sandbox, { filename: 'api/pagina-destino.js' });
const d = Object.assign({}, seed.BASE, { fotos: [{ url: seed.HERO }], tags: seed.TAGS, rating: 4.9, total_resenas: 12, creado_en: new Date(), actualizado_en: new Date() });
const html = sandbox.module.exports.buildHTML(d, {}, [], []);
function check(label, cond) { console.log((cond ? 'PASS' : 'FAIL') + ' - ' + label); if (!cond) process.exitCode = 1; }
check('renderiza sin error (len>5000)', typeof html === 'string' && html.length > 5000);
check('Titulo Barichara', html.includes('Barichara') && html.includes('Pueblo'));
check('Lead con Santander', html.includes('Santander'));
check('Coordenadas reales de Barichara', html.includes('6.636111') || html.includes('6.636'));
check('Sobre este lugar con descripcion', html.includes('id="descripcion"') && html.includes('Guanent'));
check('Camino Real a Guane', html.includes('Guane') && html.includes('Camino Real'));
check('Secretos con piedra amarilla', html.includes('piedra amarilla') || html.includes('piedra'));
check('Que llevar (equipamiento)', html.includes('que-llevar') || html.includes('Calzado'));
check('FAQ de como llegar', html.includes('Bucaramanga') || html.includes('Llego'));
const opens = (html.match(/<div/g) || []).length;
const closes = (html.match(/<\/div>/g) || []).length;
console.log('divs open=' + opens + ' close=' + closes + ' diff=' + (opens - closes));
check('balance de divs', opens === closes);