const seed = require('./seed-morat-bogota.js');
global.require_orig = require;
const Module = require('module');
const path = require('path');
const origResolve = Module._resolveFilename;
Module._resolveFilename = function(request, ...args) {
  if (request === '@neondatabase/serverless') return path.join(__dirname, 'fake_neon.js');
  return origResolve.call(this, request, ...args);
};
require('fs').writeFileSync(path.join(__dirname, 'fake_neon.js'), 'module.exports = { neon: function(){ return function(){ return []; }; } };');
const fs = require('fs');
const vm = require('vm');
const src = fs.readFileSync(path.join(__dirname, '..', 'api', 'pagina-destino.js'), 'utf8');
const sandbox = { module: { exports: {} }, require, console, process };
sandbox.exports = sandbox.module.exports;
vm.createContext(sandbox);
const wrapped = src + '\nmodule.exports.buildHTML = buildHTML;';
vm.runInContext(wrapped, sandbox, { filename: 'api/pagina-destino.js' });
const d = Object.assign({}, seed.BASE, { fotos: [{ url: seed.HERO }], tags: seed.TAGS, rating: 4.8, total_resenas: 3, creado_en: new Date(), actualizado_en: new Date() });
const html = sandbox.module.exports.buildHTML(d, {}, [], []);
function check(label, cond) { console.log((cond ? 'PASS' : 'FAIL') + ' - ' + label); if (!cond) process.exitCode = 1; }
check('renderiza sin error (len>5000)', typeof html === 'string' && html.length > 5000);
check('Fecha y sede con fechas formateadas', html.includes('id="evento-fechas"') && html.includes('14 de Agosto de 2026') && html.includes('23 de Agosto de 2026'));
check('Edicion y sede en tarjetas', html.includes('Ya Es Manana World Tour') && html.includes('Movistar Arena, Bogota'));
check('Lineup con Morat', html.includes('id="lineup"') && html.includes('Morat') && html.includes('9:00 pm'));
check('Agenda con 6 conciertos', (html.match(/Concierto/g) || []).length >= 6 && html.includes('Casa Morat'));
check('Tipos de entrada con Agotado/Disponible', html.includes('id="tipos-entrada"') && html.includes('tip-red') && html.includes('Agotado') && html.includes('Disponible'));
check('Que llevar / prohibido', html.includes('id="que-llevar"') && html.includes('Boleteria oficial') && html.includes('Camaras profesionales'));
check('Mapa con coordenadas Movistar Arena', html.includes('4.6652') || html.includes('4.6652,-74.0839'));
const opens = (html.match(/<div/g) || []).length;
const closes = (html.match(/<\/div>/g) || []).length;
console.log('divs open=' + opens + ' close=' + closes + ' diff=' + (opens - closes));
check('balance de divs', opens === closes);