const seed = require('./seed-jazz-al-parque.js');
global.require_orig = require;
const Module = require('module');
const path = require('path');
const origResolve = Module._resolveFilename;
Module._resolveFilename = function(request, ...args) {
  if (request === '@neondatabase/serverless') return path.join(__dirname, 'fake_neon.js');
  return origResolve.call(this, request, ...args);
};
require('fs').writeFileSync(path.join(__dirname, 'fake_neon.js'), 'module.exports = { neon: function(){ return function(){ return []; }; } };');
const fs = require('fs');
const vm = require('vm');
const src = fs.readFileSync(path.join(__dirname, '..', 'api', 'pagina-destino.js'), 'utf8');
const sandbox = { module: { exports: {} }, require, console, process };
sandbox.exports = sandbox.module.exports;
vm.createContext(sandbox);
const wrapped = src + '\nmodule.exports.buildHTML = buildHTML;';
vm.runInContext(wrapped, sandbox, { filename: 'api/pagina-destino.js' });
const d = Object.assign({}, seed.BASE, { fotos: [{ url: seed.HERO }], tags: seed.TAGS, rating: 4.8, total_resenas: 3, creado_en: new Date(), actualizado_en: new Date() });
const html = sandbox.module.exports.buildHTML(d, {}, [], []);
function check(label, cond) { console.log((cond ? 'PASS' : 'FAIL') + ' - ' + label); if (!cond) process.exitCode = 1; }
check('renderiza sin error (len>5000)', typeof html === 'string' && html.length > 5000);
check('Fecha y sede con fechas formateadas', html.includes('id="evento-fechas"') && html.includes('12 de Septiembre de 2026') && html.includes('13 de Septiembre de 2026'));
check('Edicion 29 y sede', html.includes('Edicion 29') && html.includes('Parque El Country, Bogota'));
check('Lineup con artista', html.includes('id="lineup"') && html.includes('Artistas nacionales e internacionales'));
check('Agenda con 2 dias', (html.match(/Todo el dia/g) || []).length >= 2 && html.includes('id="agenda"'));
check('Tipos de entrada Gratis', html.includes('id="tipos-entrada"') && html.includes('Gratis') && html.includes('Disponible'));
check('Que llevar / prohibido', html.includes('id="que-llevar"') && html.includes('Protector solar') && html.includes('Ingreso de armas'));
check('Mapa con coordenadas Parque El Country', html.includes('4.6986') || html.includes('4.6986,-74.0304'));
const opens = (html.match(/<div/g) || []).length;
const closes = (html.match(/<\/div>/g) || []).length;
console.log('divs open=' + opens + ' close=' + closes + ' diff=' + (opens - closes));
check('balance de divs', opens === closes);